// Auto-generated by scripts/generateImportMap.js
export const importMap = {
  "Core/DiscordWebhooks/frontend/page.tsx": () => import("../../module_system/Core/DiscordWebhooks/frontend/page.tsx"),
  "Core/FileBrowser/frontend/page.tsx": () => import("../../module_system/Core/FileBrowser/frontend/page.tsx"),
};
